anki_endpoint: "localhost:1234"
dictionnary_file: "dict.txt"
dictionnary_endpoint: ""
ngrams_output: "ngrams.txt"
max_ngram_len: 5
input:
  - '/home/cyril/Downloads/books/헤밍웨이, 어니스트 _ 헤밍웨이, - 노인과 바다 (2012_2013, 더클래식) - libgen.li.epub'
  - '/home/cyril/Downloads/books/한강 - 소년이 온다 (2016, (주)창비) - libgen.li.epub'

output_dir: 'output'

